server:
  port: 8808
spring:
  application:
    name: gateway
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true #开启自动识别nacos服务
      routes:
        - id: order_consumer #路由的唯一标识，路由到那
          uri: http://localhost:8802 #lb://注册中心的服务名 lb：使用nacos中的本地负载均衡
          predicates: #断言规则
            - Path=/order-server/** #http://localhost:8802/order-server/order/add
          filters:
            - StripPrefix=1 #过滤 转发之前去掉第一层路径 http://localhost:8802/order/add
