spring:
  application:
    name: seata-stock
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k12code.online:3306/stock?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 333333
     #   Druid数据源配置
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
  cloud:
    nacos:
      server-addr: 192.168.26.150:8850
      discovery:
        namespace: seata-space
        group: SEATA_GROUP
        username: nacos
        password: nacos

mybatis:
  mapper-locations: classpath:mapper/**.xml
server:
  port: 8807
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.20.150:8850
      username: nacos
      password: nacos
      group: SEATA_GROUP
      application: seata-server
      namespace: seata-space
      cluster: default
  config:
    type: nacos
    nacos:
      server-addr: 192.168.20.150:8850
      username: nacos
      password: nacos
      group: SEATA_GROUP
      namespace: seata-space
      data-id: seataServer.properties
  tx-service-group: beijing

