server:
  port: 8802
spring:
  application:
    name: producer-nacos
  cloud:
    nacos:
      server-addr: 192.168.26.150:8847
      discovery:
        namespace: localhost
        username: nacos
        password: nacos
        cluster-name: clusterNode

